version: "3"
services:
  app:
    image: node:8-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    command: sh -c "apk update && apk add docker && yarn install && yarn dev"
volumes:
  node_modules:
